#!/bin/sh
#

for arg in "$@"
do
	if [ "$arg" = "refs/heads/dev" ]
	then
		AUTHOR_NAME=$(git log -1 --format=%aN --branches dev)
		winrs -r:mydevserver python -u iis-web-deployer.py -w mysite -p c:\\inetpub\\wwwroot\\mysite -c Web-DEV.config -b dev -u "$AUTHOR_NAME" -a dude1@test.com dude2@test.com dude3@test.com
	fi
done
